Implemented cancle appointment logic on backend and unit tests
PSW-2020-ORG3/MQuince pull request #21
Opened 2020-12-11 04:09 UTC by aca24

2020-12-12 00:33 UTC, dusancina98 requested changes

2020-12-12 00:33 UTC, dusancina98 commented on MQuince/MQuince.Services.Implementation/AppointmentService.cs
> +        public Appointment CancelAppointment(Guid IdAppointment, DateTime today)
Method return type sholud be boolean to ensure if Appointment is canceled or not.
You can get current date with DateTime.Now. Method parameter 'today' is not necessary

2020-12-12 00:33 UTC, dusancina98 commented on MQuince/MQuince.Services.Implementation/AppointmentService.cs
> +        public Appointment GetAppointment(Guid id)
Method GetById for Appointment is already implemented.

2020-12-12 00:33 UTC, dusancina98 commented on MQuince/MQuince.Services.Tests/UnitTests/AppointmentTests.cs
> +        private static IAppointmentRepository CreateWorkTimeStubRepository()
Do you create Appointment Stub Repository or Work Time Stub Repository?

2020-12-12 00:33 UTC, dusancina98 commented on MQuince/MQuince.Services.Tests/UnitTests/AppointmentTests.cs
> +        public void Cancel_appointment_invalid_data()
From Test method name we don't see what is input and expected result

2020-12-12 13:38 UTC, zindovicstefan requested changes
Following requested changes are not implemented:
Method GetById for Appointment is already implemented. Use it instead getAppointment
Method return type sholud be boolean to ensure if Appointment is canceled or not.

2020-12-13 02:44 UTC, zindovicstefan requested changes
‎As we have discussed earlier this branch in this state introduces breaking change. Because appointment entity is modified to support logical deletion by adding additional boolean property, repository methods don't work properly anymore. Each method which fetches appointments from database should be modified to check if appointment is logically deleted.

2020-12-13 17:59 UTC, zindovicstefan requested changes
Update feature branch with develop branch, Integration and Unit Tests need to be in correct namespace so tests can run in CI pipeline. CI pipeline failed so this changes can not be approved. Build fails on add-migration locally when branch is updated with develop. With @dusancina98 I tried multiple times to add migration each times unsuccessfully. We can't approve this changes day before sprint review, high possibility to introduce problems with continuous delivery to heroku.

2020-12-13 18:05 UTC, zindovicstefan commented
This branch has conflicts that must be resolved before merging to develop. Update branch with changes from develop before PR. Conflicting file are listed under CI pipeline checks on this page.

2020-12-30 23:40 UTC, closed without merging