Add unit tests for appointment service
PSW-2020-ORG3/MQuince pull request #25
Opened 2020-12-12 14:49 UTC by jelena-petkovic

2020-12-12 15:19 UTC, zindovicstefan requested changes
Implement requested changes

2020-12-12 15:19 UTC, zindovicstefan commented on MQuince/MQuince.Services.Tests/AppointmentTests.cs
> +        public void Constructor_when_give_repository_as_null()
Implement a method for every argument, Constructor when given [argument name] null, and check if constructor throws ArgumentNullException if tested argument is null.

2020-12-12 15:45 UTC, zindovicstefan approved these changes

2020-12-12 17:45 UTC, dusancina98 requested changes

2020-12-12 17:45 UTC, dusancina98 commented on MQuince/MQuince.Services.Tests/AppointmentTests.cs
> +        private bool CompareAppointmentsForDoctorForDate(List<Appointment> appointemntsFirst, List<IdentifiableDTO<AppointmentDTO>> appointemntsSecond, DateTime date)
This method should be refactored.

2020-12-13 03:50 UTC, zindovicstefan approved these changes

2020-12-13 13:33 UTC, zindovicstefan approved these changes

2020-12-13 16:43 UTC, dusancina98 approved these changes

2020-12-13 16:43 UTC, dusancina98 approved these changes

2020-12-13 16:44 UTC, merged