Initialize integration adapter project
PSW-2020-ORG3/MQuince pull request #4
Opened 2020-12-01 21:25 UTC by saradj411

Sara Djuric:implement sftp,implement pdf generator feature
Kristina Mucibabic: implement rabbitMQ, create database
Verica Mucibabic:implement rabbitMQ, create database
Maja Milenkovic:implement pharmacy registration feature, implement
frontend
All: add unit tests, implement persistance entities

2020-12-03 00:00 UTC, dusancina98 approved these changes
A few more places for future refactor, but it's a lot better than last commit.

2020-12-03 00:00 UTC, dusancina98 commented on MQuince/MQuince.Integration.Services.Implementation/MedicationsConsumptationService.cs
> +        public void GeneratePdf(DateDTO dto)
This method could be refactored. Creating a new Class (eg. PdfGenerator) with couple of methods should do the job. But this is a lot better then in last commit.

2020-12-03 00:00 UTC, dusancina98 commented on MQuince/MQuince.Integration.Services.Implementation/SftpService.cs
> +        public bool SendFile(string fileName)
This is a good place for refactoring in couple of methods. 
Throwing exception when client is not connected and handling in controller is better way of telling if the operation was succesfull. Then you can change return type to void.

2020-12-03 00:00 UTC, dusancina98 commented on MQuince/MQuince.Integration.HospitalApp/Startup.cs
> +            dbContextOptionsBuilder.UseMySql(@"server=localhost;user=root;password=root;database=pharmacydb");
Take a look at the MQuince.Application project from web team and appsettings.json from MQuince.WebAPI project.
You can make it more configurable by storing connection string in configuration file.

2020-12-03 00:50 UTC, zindovicstefan requested changes
Commented regions should be resolved before PR is approved

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp.Tests/MedicationsConsumptationMapperTest.cs
> +            Assert.NotNull(medicationsConsumptation);
Assert should check if each property is mapped correctly, to assert that return value of method is not null is not enough

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp.Tests/MedicationsConsumptationMapperTest.cs
> +            Assert.NotNull(persistance);
Assert should check if each property is mapped correctly, to assert that return value of method is not null is not enough

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp.Tests/OperationsWithDatabaseTest.cs
> +            Assert.NotNull(service.Create(pharmacy));
Assert doesn't check if repository state is changed, just that returned value is not null

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp.Tests/PharmacyMapperTest.cs
> +            Assert.NotNull(pharmacy);
Assert should check if each property is mapped correctly, to assert that return value of method is not null is not enough

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp.Tests/PharmacyMapperTest.cs
> +            Assert.NotNull(pharmacyPersistance);
Assert should check if each property is mapped correctly, to assert that return value of method is not null is not enough

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp/Controllers/MedicationsConsumptationController.cs
> +            return Ok(dto);
http response code is not always 200 ok

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp/Controllers/PharmacyController.cs
> +            return Ok(dto);
http response code is not always 200 ok

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.HospitalApp/RabbitMQService.cs
> +    public class RabbitMQService : BackgroundService
This class should be refactored

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.Repository.MySQL/DataProvider/MedicationsConsumptionRepository.cs
> +            throw new NotImplementedException();
Implement or remove method

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.Repository.MySQL/DataProvider/PharmacyRepository.cs
> +            throw new NotImplementedException();
Implement or remove method

2020-12-03 00:50 UTC, zindovicstefan commented on MQuince/MQuince.Integration.Services.Implementation/PharmacyService.cs
> +        }
Implement or remove methods

2020-12-04 22:19 UTC, zindovicstefan approved these changes
All commented flaws are successfully resolved. All features from now on should be implemented using specified git workflow and git commit message format.

2020-12-04 22:20 UTC, merged